filter:
    excluded_paths:
        - 'tests/*'
        - 'vendor/*'
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"

checks:
    php:
        code_rating: true
        duplication: true
        
build:
    environment:
        php:
            version: 5.6
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - mysql -u root -e "CREATE DATABASE icinga_editor"
            - mysql -u root -e "GRANT ALL PRIVILEGES ON icinga_editor.* TO icinga_editor@localhost IDENTIFIED BY 'LojAstod9'"
            - composer self-update
            - composer install --no-interaction --prefer-source
            - ./vendor/bin/phinxmigrate -c ./phinx-adapter.php
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover'
                coverage:
                    file: 'clover'
                    format: 'php-clover'
