#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
        . /usr/share/dbconfig-common/dpkg/config.mysql
        dbc_dbuser="icinga_editor"
        dbc_dbname="icinga_editor"
        if ! dbc_go icinga-editor $@ ; then
            echo 'Automatic configuration using dbconfig-common failed!'
        fi
fi

db_version 2.0

db_input high icinga-editor/reconfigure-webserver || true
db_go || true

db_input critical icinga-editor/SEND_MAILS_FROM || true
db_go || true

db_input critical icinga-editor/ICINGA_SERVER_IP || true
db_go || true
