#!/bin/sh
# postinst script for icinga-editor

set -e

apache_install() {
	COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)

	if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
		. /usr/share/apache2/apache2-maintscript-helper
		apache2_invoke enconf icinga-editor
	elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
		[ -d /etc/apache2/conf.d/ ] && [ ! -L /etc/apache2/conf.d/icinga-editor.conf ] && ln -s ../conf-available/icinga-editor.conf /etc/apache2/conf.d/icinga-editor.conf
	fi
}

IECFG="/usr/share/icinga-editor/includes/Configure.php"

if [ ! -f $IECFG ] ; then

    . /usr/share/debconf/confmodule

    db_input critical icinga-editor/SEND_MAILS_FROM || true
    db_go || true
    db_get icinga-editor/SEND_MAILS_FROM

    db_input critical icinga-editor/ICINGA_SERVER_IP || true
    db_go || true
    db_get icinga-editor/ICINGA_SERVER_IP



    . /usr/share/dbconfig-common/dpkg/postinst.mysql
    dbc_generate_include_owner="root:www-data"
    dbc_generate_include_perms="0640"
    dbc_generate_include=sh:/etc/icinga-editor/config-db.sh


    if ! dbc_go icinga-editor $@ ; then
            echo 'Automatic configuration using dbconfig-common failed!'
    fi

    . /etc/icinga-editor/config-db.sh


    echo > $IECFG 
    echo "<?php" >> $IECFG 
    echo "define('SEND_MAILS_FROM', '$SEND_MAILS_FROM');" >> $IECFG 
    echo "define('DB_TYPE', 'mysql');" >> $IECFG 
    echo "define('DB_SERVER', 'localhost');" >> $IECFG 
    echo "define('DB_SERVER_USERNAME', '$dbuser');" >> $IECFG 
    echo "define('DB_SERVER_PASSWORD', '$dbpass');" >> $IECFG 
    echo "define('DB_DATABASE', '$dbname');" >> $IECFG 
    echo "define('DB_PREFIX', '');" >> $IECFG 
    echo "define('LOG_DIRECTORY', '/var/log/');" >> $IECFG 
    echo "define('CFG_GENERATED', '/etc/icinga/generated/');" >> $IECFG 
    echo "define('LOG_NAME', 'IcingaEditor');" >> $IECFG 
    echo "define('LOG_TYPE', 'syslog');" >> $IECFG 

    IWCFG="/etc/dbconfig-common/icinga-web.conf"
    IW_SERVER_USERNAME=`cat $IWCFG | grep dbc_dbuser= | awk -F\' '{print $2}'`
    IW_SERVER_PASSWORD=`cat $IWCFG | grep dbc_dbpass= | awk -F\' '{print $2}'`
    IW_DATABASE=`cat $IWCFG | grep dbc_dbname= | awk -F\' '{print $2}'`

    echo "define('DB_IW_SERVER_USERNAME', '$IW_SERVER_USERNAME');" >> $IECFG 
    echo "define('DB_IW_SERVER_PASSWORD', '$IW_SERVER_PASSWORD');" >> $IECFG 
    echo "define('DB_IW_DATABASE', '$IW_DATABASE');" >> $IECFG 



    #rm -f /etc/icinga-editor/config-db.sh
    #(Moved To links file) ln -s   /usr/share/icinga/htdocs/images/logos /usr/share/icinga-editor/logos
    

    if [ "$1" = "configure" ]; then

            db_version 2.0

            mkdir -p /usr/share/icinga-editor/log
            mkdir -p /usr/share/icinga-editor/temp
            mkdir -p /usr/share/icinga/htdocs/images/logos/custom

            chown -R www-data:www-data    /etc/icinga/generated
            chown -R www-data:www-data    /usr/share/icinga-editor/log
            chown -R www-data:www-data    /usr/share/icinga-editor/temp
            chown -R www-data:www-data    /usr/share/icinga/htdocs/images/logos/custom

            apache_install $1
                    # Reload webserver in any case, configuration might have changed
                    # Redirection of 3 is needed because Debconf uses it and it might 
                    # be inherited by webserver. See bug #446324.
            if [ -f /etc/init.d/apache2 ] ; then
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d apache2 reload 3>/dev/null || true
                else
                    /etc/init.d/apache2 reload 3>/dev/null || true
                fi
            fi

            if [ -f /etc/init.d/avahi ] ; then
                if [ -x /usr/sbin/invoke-rc.d ]; then
                    invoke-rc.d avahi reload 3>/dev/null || true
                else
                    /etc/init.d/avahi reload 3>/dev/null || true
                fi
            fi

            # Import configuration Question ?
            db_input medium icinga-editor/IMPORT_CONFIG || true
            db_go

            # Check their answer.
            db_get icinga-editor/IMPORT_CONFIG
            if [ "$RET" = "true" ]; then
                iecfgimporter
            fi
    fi

fi

cd /usr/share/icinga-editor

if [ -f composer.lock ] ; then
    rm composer.lock
fi

composer --no-dev -o update

#DEBHELPER#

exit 0
