#!/bin/sh
# postinst script for icinga-editor

set -e

#Replace Key Value in PhinX Config File
replaceYML() {
    cfg="/var/lib/icinga-editor/phinx.yml"
    sed -i "/${1}:/c\        ${1}: ${2}" $cfg
}

replaceJSON() {
    cfg="/etc/icinga-editor/config.json"
    sed -i "/${1}/c\        \"${1}\": \"${2}\"," $cfg
}


. /usr/share/debconf/confmodule

db_input critical icinga-editor/SEND_MAILS_FROM || true
db_go || true
db_get icinga-editor/SEND_MAILS_FROM
SEND_MAILS_FROM=$RET

db_input critical icinga-editor/ICINGA_SERVER_IP || true
db_go || true
db_get icinga-editor/ICINGA_SERVER_IP
ICINGA_SERVER_IP=$RET


. /usr/share/dbconfig-common/dpkg/postinst.mysql
dbc_dbuser="icinga_editor"
dbc_dbname="icinga_editor"
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=sh:/etc/icinga-editor/config-db.sh

if ! dbc_go icinga-editor $@ ; then
        echo 'Automatic configuration using dbconfig-common failed!'
fi

. /etc/icinga-editor/config-db.sh


IWCFG="/etc/dbconfig-common/icinga-web.conf"
IW_SERVER_USERNAME=`cat $IWCFG | grep dbc_dbuser= | awk -F\' '{print $2}'`
IW_SERVER_PASSWORD=`cat $IWCFG | grep dbc_dbpass= | awk -F\' '{print $2}'`
IW_DATABASE=`cat $IWCFG | grep dbc_dbname= | awk -F\' '{print $2}'`


replaceJSON "DB_IW_SERVER_USERNAME" $IW_SERVER_USERNAME
replaceJSON "DB_IW_SERVER_PASSWORD" $IW_SERVER_PASSWORD
replaceJSON "DB_IW_DATABASE" $IW_DATABASE

if [ "$1" = "configure" ]; then

        db_version 2.0

        mkdir -p /usr/share/icinga-editor/log
        mkdir -p /usr/share/icinga-editor/temp
        mkdir -p /usr/share/icinga/htdocs/images/logos/custom

        chown -R www-data:www-data    /etc/icinga/generated
        chown -R www-data:www-data    /usr/share/icinga-editor/log
        chown -R www-data:www-data    /usr/share/icinga-editor/temp
        chown -R www-data:www-data    /usr/share/icinga/htdocs/images/logos/custom

        if [ -f /etc/init.d/apache2 ] ; then
            a2enconf icinga-editor
            service apache2 reload
        fi

        if [ -f /etc/init.d/avahi ] ; then
            service avahi reload
        fi

fi


cd /usr/share/icinga-editor

if [ -f composer.lock ] ; then
    rm composer.lock
fi

composer --no-dev -o update

    . /etc/icinga-editor/config-db.sh

replaceJSON "DB_TYPE" "mysql"
replaceJSON "DB_HOST" "localhost"
replaceJSON "DB_USERNAME" $dbuser
replaceJSON "DB_PASSWORD" $dbpass
replaceJSON "DB_DATABASE" $dbname
replaceJSON "DB_PREFIX" ""
replaceJSON "SEND_MAILS_FROM" $SEND_MAILS_FROM

replaceYML "adapter"    "mysql"
replaceYML "host"       "localhost"
replaceYML "port"       3306
replaceYML "user"       $dbuser
replaceYML "pass"       $dbpass
replaceYML "name"       $dbname

phinx -n -c/var/lib/icinga-editor/phinx-adapter.php migrate -e production


# Import configuration Question ?
db_input medium icinga-editor/IMPORT_CONFIG || true
db_go

# Check their answer.
db_get icinga-editor/IMPORT_CONFIG
if [ "$RET" = "true" ]; then
    iecfgimporter /etc/icinga/icinga.cfg
fi


#DEBHELPER#

exit 0
