.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH iecfgimporter 1 "August 2, 2016" "" "Icinga Editor Config importer"

.SH NAME
iecfgimporter \- program for import icinga/nagios config files into Icinga Editor database

.SH SYNOPSIS
.B iecfgimporter <config file>
.br

.SH DESCRIPTION
This manual page explains the use of 
.B iecfgimporter
Simply run /usr/bin/iecfgimporter /etc/icinga/icinga.cfg. It read all configuration files in and import it into Icinga Editor database. Thus you can generate an copy of original configuration from web interface.
.PP
\fBiecfgimporter\fP is for initial database population.

.SH "SEE ALSO"
https://github.com/VitexSoftware/Icinga-Editor
